### PR TITLE
Workaround to don't ask Password (set password to nothing)

### PR DESCRIPTION
**Pull request by Burnfaker**

### CODE REVIEW

**Comment by mk-fg** [comment]
Thanks!

Recent ssh-keygen indeed doesn't seem to work non-interactively as invoked in the script, so some fix is necessary.

Unfortunately, could not get this one to work here with openssh 6.7_p1 - ssh-keygen fails and dracut blocks forever on fifo, so did a revert in 2cca989.

Apologies if it's a bit of a redundant question, but does it work for you?
If so, can you tell which version of openssh you're using and maybe if you have some non-distro/openssh-default stuff in configuration files (though not sure if ssh-keygen reads any)?

**Comment by mk-fg** [comment]
Correction: just discovered that you had a typo in the commit, missing a single quote mark. Fixed.

**Comment by Burnfaker** [comment]
True bro. I'm sorry

I'll make a few Changes. But i cant load this module with Dracut on Fedora 21.
I don't know why... not yet

**Comment by mk-fg** [comment]
I've fixed the typo in the follow-up commit, so if by Changes you mean that one - shouldn't be necessary.
In fact, dunno if I've missed -N option before, or if it didn't work for me or something, but there was a lot of unnecessary wrapping around ssh-keygen (script, mkfifo, subshell), which I was able to drop, making this weird quoting rather unnecessary.

It seem to build initramfs here with rather recent dracut-040.
I didn't actually try to reboot with this change, but I imagine it should work, as change only concerns ssh-keygen.

**Comment by Burnfaker** [comment]
I mean not the quotes. I will make a few changes

**Pull request merged**
